[project]
name = "learningsparkv2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.9"
dependencies = [
    "cloudpickle>=3.1.1",
    "notebook>=7.4.4",
    "py4j>=0.10.9.5",
    "pyspark==3.3.1",
]
